// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1XUWQ8L-zF3_jNw6QBWJuM_5QXE609U8',
    appId: '1:555192082112:web:11ee37bea1ac820cac1725',
    messagingSenderId: '555192082112',
    projectId: 'hydroponix-1b993',
    authDomain: 'hydroponix-1b993.firebaseapp.com',
    storageBucket: 'hydroponix-1b993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAT_eWp5xfL3dOtFt8XJfgGo7q4nE2sxA',
    appId: '1:555192082112:android:fe1cdff75a980971ac1725',
    messagingSenderId: '555192082112',
    projectId: 'hydroponix-1b993',
    storageBucket: 'hydroponix-1b993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4K3OqpWTsv18KeiHcI0WI4p3IIr7lMGo',
    appId: '1:555192082112:ios:faa8faced5e7975dac1725',
    messagingSenderId: '555192082112',
    projectId: 'hydroponix-1b993',
    storageBucket: 'hydroponix-1b993.appspot.com',
    iosBundleId: 'com.example.hydroponx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4K3OqpWTsv18KeiHcI0WI4p3IIr7lMGo',
    appId: '1:555192082112:ios:faa8faced5e7975dac1725',
    messagingSenderId: '555192082112',
    projectId: 'hydroponix-1b993',
    storageBucket: 'hydroponix-1b993.appspot.com',
    iosBundleId: 'com.example.hydroponx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1XUWQ8L-zF3_jNw6QBWJuM_5QXE609U8',
    appId: '1:555192082112:web:4c1930ad1aee3939ac1725',
    messagingSenderId: '555192082112',
    projectId: 'hydroponix-1b993',
    authDomain: 'hydroponix-1b993.firebaseapp.com',
    storageBucket: 'hydroponix-1b993.appspot.com',
  );

}